/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LightWebDevelopmentRouteImport } from './routes/light.web-development'
import { Route as DarkCybersecurityRouteImport } from './routes/dark.cybersecurity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LightWebDevelopmentRoute = LightWebDevelopmentRouteImport.update({
  id: '/light/web-development',
  path: '/light/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkCybersecurityRoute = DarkCybersecurityRouteImport.update({
  id: '/dark/cybersecurity',
  path: '/dark/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dark/cybersecurity': typeof DarkCybersecurityRoute
  '/light/web-development': typeof LightWebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dark/cybersecurity': typeof DarkCybersecurityRoute
  '/light/web-development': typeof LightWebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dark/cybersecurity': typeof DarkCybersecurityRoute
  '/light/web-development': typeof LightWebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dark/cybersecurity'
    | '/light/web-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dark/cybersecurity'
    | '/light/web-development'
  id:
    | '__root__'
    | '/'
    | '/dark/cybersecurity'
    | '/light/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DarkCybersecurityRoute: typeof DarkCybersecurityRoute
  LightWebDevelopmentRoute: typeof LightWebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light/web-development': {
      id: '/light/web-development'
      path: '/light/web-development'
      fullPath: '/light/web-development'
      preLoaderRoute: typeof LightWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark/cybersecurity': {
      id: '/dark/cybersecurity'
      path: '/dark/cybersecurity'
      fullPath: '/dark/cybersecurity'
      preLoaderRoute: typeof DarkCybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DarkCybersecurityRoute: DarkCybersecurityRoute,
  LightWebDevelopmentRoute: LightWebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
